project:
  name: quickstart-eks-rafay-systems
  owner: quickstart-eng@amazon.com
  regions: ["us-west-2"]
  template: templates/eks-rafay.template.yaml
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    EksClusterName: --override--
tests:
  new-customer:
    parameters:
      FirstName: --override--
      LastName: --override--
      OrganizationName: --override--
      Email: --override--
  existing-customer:
    parameters:
      ApiKey: --override--
      ApiSecret: --override--