project:
  name: quickstart-eks-rafay-systems
  owner: quickstart-eng@amazon.com
  regions:
    - af-south-1
    - ap-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-southeast-3
    - ca-central-1
    - eu-central-1
    - eu-north-1
    - eu-south-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - us-gov-east-1
    - us-gov-west-1
    - cn-north-1
    - cn-northwest-1
  template: templates/eks-rafay.template.yaml
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    EksClusterName: --override--
tests:
  new-customer:
    parameters:
      FirstName: --override--
      LastName: --override--
      OrganizationName: --override--
      Email: --override--
    regions:
      - us-west-2
  existing-customer:
    parameters:
      ApiKey: --override--
      ApiSecret: --override--
    regions:
      - us-west-2
