// Replace the content in <>
// Identify your target audience and explain how/why they would use this Quick Start.
//Avoid borrowing text from third-party websites (copying text from AWS service documentation is fine). Also, avoid marketing-speak, focusing instead on the technical aspect.

This guide provides instructions to leverage Rafay’s Managed Kubernetes Platform (MKP) for Amazon Elastic Kubernetes Service (EKS) management and operations.

Rafay’s Managed Kubernetes Platform lets users easily deploy, operate & manage the lifecycle of Kubernetes clusters and containerized applications in both public-cloud and on-premises environments.

This Quick Start is for professionals who want to deploy Kubernetes clusters in AWS Cloud, in data centers, or at the Edge. From MKP’s SaaS-based management console, professionals can automate multi-cluster provisioning, configuration management & upgrades for Kubernetes clusters. MKP also automates containerized application deployment and enables developer access to Kubernetes clusters through a unique, zero-trust connectivity model. Additionally, MKP delivers enterprise-grade capabilities such as single-pane-of-glass monitoring & visibility across AWS regions, cross-cloud role-based access control, and governance.

=== MKP for AWS

Rafay users can provision and manage lifecycle for Kubernetes clusters in both cloud and on-premises environments. In public cloud environments, complete lifecycle management of the natively available managed Kubernetes service (e.g. EKS in AWS) is supported. 

*Complete lifecycle management for natively available managed Kubernetes services (e.g. EKS)* clusters is supported on the MKP, where users can programmatically (or via the MKP console) create and configure EKS clusters, along with core infrastructure components (that is, compute, storage, and networking). This capability is designed to be an automated experience for users. For high availability (HA) clusters, MKP automatically provisions master nodes in different Availability Zones (AZs).

*Complete lifecycle management for Kubernetes clusters deployed on-premises or at the Edge* can be carried our programmatically (or via the MKP console) by users. This approach is agnostic to the type and provider of the underlying infrastructure, and is designed to work with bare metal servers and virtual machines (VMs).

Pre-existing clusters can easily be imported into MKP. When clusters provisioned or imported into MKP, MKP provides a single pane of glass that provides visibility and lifecycle management of applications and clusters across all environments. The benefits of this include, but not limited to, the following:

*Single pane-of-glass management across AWS Regions and on-premises*: Use a single console to deploy, view, and manage clusters and workloads across all clusters.

*Accelerate migration to AWS:* With Rafay, Amazon EKS clusters can be running in minutes (including Spot Instances), and applications can be deployed in even less time.

*Apply enterprise-grade K8 security on AWS*: Rafay’s zero-trust architecture for Kubernetes lets enterprises  cloak their Kubernetes API endpoints on AWS without affecting CI/CD and developer workflows.

*Multi-cluster application deployment across any environment:* Rafay’s zero-trust architecture for Kubernetes lets enterprises deploy containerized applications easily using their existing CI/CD systems or via Rafay’s turnkey gitops feature set.
